### ISSUE TITLE
Add safeguards to prevent deleting leftover PVs as part of extended-cleanup-rancher2.sh 

### ISSUE THREAD

**Issue by mattmattox** [rancherlabs/support-tools#106]
It looks like if a PV gets left mounted under /var/lib/kubelet, the cleanup script will `rm -rf` it as part of https://github.com/rancherlabs/support-tools/blob/b7782a2ff379bcd0b9d0e27feab233efb24dbede/extended-rancher-2-
cleanup/extended-cleanup-rancher2.sh#L55

We need to add some safeguards to the script to look for all mounted filesystem under /var/lib/kubelet and try unmounting and error out if it can't.

**Comment by dkeightley** [comment]
Closing in favour of https://github.com/rancherlabs/support-tools/issues/140
