### ISSUE TITLE
Add safeguards to prevent deleting leftover PVs as part of extended-cleanup-rancher2.sh ++

### ISSUE THREAD

**Issue by Tejeev** [rancherlabs/support-tools#140]
We are still seeing the cleanup script getting stuck trying to rm container volumes with still mounted nfs mount points. 

```/var/lib/kubelet/pods/06dd64f1-bb2a-411d-9192-0aab6e7cbc73/volumes/kubernetes.io~nfs/nfs-mount-prd/prod/rancher```
```du: cannot access ‘./06dd64f1-bb2a-411d-9192-0aab6e7cbc73/volumes/kubernetes.io~nfs/nfs-mount-prd-binarystore/prod/rancher/artifactory-ha/data/filestore/17/17c6c483e99a0a604e27e87f5631989f2d5bf2c5’: No such file or directory```

The customer is using an external NFS client provisioner (quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11)

Workaround is to remove `/var/lib/kubelet/*` from the `CLEANUP_DIRS` variable in the script, which of course leaves behind directories we may wish to remove

**Comment by Tejeev** [comment]
@mattmattox wasn't sure how best to do this and since you worked with them on this previously in #106, I assigned you to it, jic you had a quick solution

**Comment by dkeightley** [comment]
Would including these in the umount prevent the following cleanup of /var/lib/kubelet?

Example which removes the focus on `tmpfs`, and rather umount everything mounted under `/var/lib/kubelet/pods`

```bash
 cleanup-dirs() {

   techo "Unmounting filesystems..."
-  for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }')
+  for mount in $(mount | grep '/var/lib/kubelet/pods' | awk '{ print $3 }')
     do
       umount $mount
   done
```

Needs some testing, perhaps `umount -f` may be needed in some cases?

**Comment by mattmattox** [comment]
What if we added a check to look for open filesystems and exit if it finds anything.

```
if ! lsof /var/lib/kubelet/;
then
  echo "Problem: There is open files in /var/lib/kubelet, please make sure that all filesystems and shares have been unmounted.
  exit 2
fi
```

Details of the lsof exit code https://stackoverflow.com/a/29843137/8412333
