### ISSUE TITLE
Cluster-agent-tool for RKE2

### ISSUE THREAD

**Issue by Scott-Wenzel** [rancherlabs/support-tools#181]
I would like to see a version of the [cluster-agent-tool](https://github.com/rancherlabs/support-tools/tree/master/cluster-agent-tool) script for downstream RKE2 clusters for when you change your Rancher url or certs.  I've currently got 4 RKE2 clusters that are sitting in "Waiting for at least one bootstrap node" in my Cluster Management list because I changed certs for my Rancher app from the default Rancher self-signed to LetsEncrypt certs.  Some kind of documentation/discussion would suffice in the interim.  Thank you!

**Comment by Scott-Wenzel** [comment]
I should add the RKE2 clusters are custom/bare metal clusters.

**Comment by Scott-Wenzel** [comment]
Is there anyone who can assist me please?

**Comment by mattmattox** [comment]
I would recommend following the steps listed at https://rancher.support/training/rancher/rancher-certs/ for changing your Rancher.

Note: Changing your root CA is not officially supported because of this issue.

**Comment by Scott-Wenzel** [comment]
Thanks for the reply Matt -  I had no problem getting the cluster-agents back up and running within the downstream clusters.  I can access the clusters via Rancher.   Issue is that these are Rancher deployed custom RKE2 clusters.  The rancher-system-agent daemon service on each node (RKE2 cluster) is erroring.   Cluster state is Provisioning, Waiting for at least one bootstrap node in the Rancher Cluster Management->Cluster dialog.   Under the Cluster, machines have all disappeared under the Cluster->Machines tab.  /var/lib/rancher/agent/rancher2_connection_info.json on each node is no longer valid.  With that, the custom-xxxx-machine-plan secret in the fleet-default namespace have disappeared.  I've tried re-registering nodes but that did not work.

**Comment by Scott-Wenzel** [comment]
@mattmattox - Any options available to move past this?
