### ISSUE TITLE
Leave /opt/rke/etcd-snapshots directory by default during cleanup

### ISSUE THREAD

**Issue by dkeightley** [rancherlabs/support-tools#189]
In scenarios where an etcd node is being cleaned, it would be ideal to leave the etcd-snapshots directory, to keep historical snapshots as a default.

**Comment by mattmattox** [comment]
Should we put this behind a flag?

For example --delete-snapshots

Or we could add warning messages like "We detected ETCD snapshots, Are you sure you want to delete them? Y/N"
