### ISSUE TITLE
Log Collector should collect kubelet logs from RKE2 nodes

### ISSUE THREAD

**Issue by Martin-Weiss** [rancherlabs/support-tools#214]
So far it seems the log collector does not include the kubelet logs of RKE2 but we need them pretty often for troubleshooting / analysis (see i.e. SURE-5781)

-> could we get the Rancher2 Log Collector enhanced to collect the kubelet logs of all nodes, too?

**Comment by dkeightley** [comment]
This should be completed already in https://github.com/rancherlabs/support-tools/pull/134/files

In the collection you should have:
```bash
# ls -al rke2/agent-logs
total 472
drwxr-xr-x 2 root root   4096 Feb 10 00:41 .
drwxr-xr-x 9 root root   4096 Feb 12 21:12 ..
-rw-r--r-- 1 root root 471837 Feb 10 00:44 kubelet.log
```

**Comment by Martin-Weiss** [comment]
Thanks - you are right it is included - but the challenge has been that we need the kubelet.log of all nodes and not just from the node where we start the logs collector..

-> is there a simple way to use the log collector "cluster wide" and create one single log bundle?

**Comment by dkeightley** [comment]
This unfortunately would fall outside of the log collector, designed to be run with minimal overhead on a per-node basis.

Coordinating a file copy from other nodes could be computationally expensive. How would it work, potentially by running a daemonset pod with a host mount to access the file? This could be seen as undesired and a security concern.

**Comment by Martin-Weiss** [comment]
So for proper support you recommend to run the log collector on all nodes manually and then fetch the resulting file? Maybe we should look into the log collector in harvester and use that instead or in addition to the current script?

**Comment by leodotcloud** [comment]
@dkeightley may be we can repurpose the supportability-review data collector for this purpose? We already have all the infrastructure in place to collect the data.

**Comment by dkeightley** [comment]
@leodotcloud I was thinking this as well, it is already set up to accommodate running the daemonset etc., we might just need to carefully limit the file size that gets retrieved as I don't think the RKE2 kubelet log gets rotated, by default at least.

**Comment by Martin-Weiss** [comment]
And we might need to think about some integration with Rancher - we have this "challenge" as well to get complete info for support of any downstream clusters..

**Comment by leodotcloud** [comment]
In the early days of Rancher, I authored a very simple web app that runs in the "local" cluster to collect logs and was downloadable from the UI itself. Need to revisit that approach with the new Rancher UI extensions.

**Comment by dkeightley** [comment]
This may be possible with the supportability-review collection, closing as this is outside of the design of the logs-collector, please re-open if I'm mistaken.
