### ISSUE TITLE
The log collector script should collect a list of network policies defined in the cluster.

### ISSUE THREAD

**Issue by kourosh7** [rancherlabs/support-tools#226]
The log collector script should collect a list of network policies defined in the cluster.

I have had cases where a NetworkPolicy was the culprit of the problem and it would have been good to see those from the beginning when requesting log bundles.

**Comment by dkeightley** [comment]
We can add this for rke2/k3s server nodes. The kubeconfig provided with rke2/k3s agent nodes, and RKE1 nodes is limited in permissions.

I'll propose a PR
