### ISSUE TITLE
[Suggestion] By default we should recommend the script be run with -i -f

### ISSUE THREAD

**Issue by willagc** [rancherlabs/support-tools#227]
The current default recommendation is as follows:

```
curl -LO https://github.com/rancherlabs/support-tools/raw/master/extended-rancher-2-cleanup/extended-cleanup-rancher2.sh

bash extended-cleanup-rancher2.sh
```
I propose changing the default recommendation, as it would help address several common issues by automatically clearing out old images and stale iptables rules. 

```
curl -LO https://github.com/rancherlabs/support-tools/raw/master/extended-rancher-2-cleanup/extended-cleanup-rancher2.sh

bash extended-cleanup-rancher2.sh -i -f
```

**Comment by dkeightley** [comment]
Thanks @willagc, the iptables rules might be a good safe default.

The images are left in case the node is to be re-used, it will speed up provisioning by already having a local copy of any matching images.

Any thoughts, do you want to propose the change in a PR? We should update the readme and help info to align with any changes.

**Comment by aemneina** [comment]
iptables flush makes sense... I'd agree that leaving images is helpful to rebuild clusters quickly, and should be omitted.
