### ISSUE TITLE
extended-cleanup-rancher2.sh deleting PVCs

### ISSUE THREAD

**Issue by mattmattox** [rancherlabs/support-tools#247]
When running the cleanup script, if a PVC is still mounted under /var/lib/kubelet. We will rm -rf it and damage the PVC.

We should umount then check if it really umounted, if yes then rm -rf else skip rm.

**Comment by dkeightley** [comment]
What do you think of https://github.com/rancherlabs/support-tools/issues/140#issuecomment-921284966 @mattmattox?

The `lsof` option would have a dependency, could also be resource intensive to run.
