### ISSUE TITLE
Feature request - Add detection of snapshots as part of cleanup

### ISSUE THREAD

**Issue by mattmattox** [rancherlabs/support-tools#249]
Right now, the cleanup will delete etcd snapshots from an etcd node. This causes issues if the cluster doesn't have backups on another node or S3.

We should detect if we see snapshots, it should throw a warning and ask "Y/N" if they are sure. Or maybe give an option to move them something else like current working dir.

**Comment by axeal** [comment]
I would even argue the default behaviour should be not to delete etcd snapshots (perhaps with a printed message that it won't delete them) and with the option to delete them via an additional flag to the script

**Comment by mattmattox** [comment]
Agreed so something 

"We have detected etcd snapshots, would you like to backup them first? Y/N"
If the user enters Y, then we copy the snapshots into another folder like the current dir.
If the user enters N, then we delete it.

I'll also add a flag like --delete-snapshots true with the default behavior being to not delete snapshots.

**Comment by dkeightley** [comment]
Looks like we've added the flag and default of keeping etcd snapshots -- https://github.com/rancherlabs/support-tools/pull/198

Where do you want to take it from here @mattmattox? I would lean towards not adding interactive prompts as well, a warning would be trivial to add to the script if you see this being useful.

**Comment by dkeightley** [comment]
Please reopen if there is anything further we should action.
