### ISSUE TITLE
log collector does not always detect RKE2 distro

### ISSUE THREAD

**Issue by kourosh7** [rancherlabs/support-tools#252]
I've had many cases where the log bundle captured from a node in an RKE2 cluster only contains the following directories:
`journald  networking  systeminfo  systemlogs`

I have to tell customers to manually add the -r rke2 parameter for the log bundle to be complete.

`curl -OLs https://raw.githubusercontent.com/rancherlabs/support-tools/master/collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh`
`sudo bash rancher2_logs_collector.sh -r rke2`

**Comment by Tejeev** [comment]
We had an occurrence of this with another customer.  Getting stdout to attach here

**Comment by leodotcloud** [comment]
@dkeightley, do you have any idea what's going on here? I guess you had implemented the detection logic in the past?

**Comment by dkeightley** [comment]
If you have an example collection please send it my way, with the output from the process list or rke2-* service logs we might be able to tell. One scenario could be a custom RKE2 install directory is used which can't be detected with the current approach.

**Comment by dkeightley** [comment]
Please reach out or reopen and we can continue solving this

**Comment by Tejeev** [comment]
Hopefully addressed by https://github.com/rancherlabs/support-tools/pull/254
