### ISSUE TITLE
rancher2_logs_collector.sh does not collect all data when rke2 is installed in /opt/rke2

### ISSUE THREAD

**Issue by megabreit** [rancherlabs/support-tools#253]
The logs collector is not able to identify the rke2 version on systems which have rke2 installed into /opt/rke2.
rke2 is installed to /opt/rke2 when /usr is read-only or on btrfs, like in the standard installation of SLES 15.

The script is checking only `command -v rke2` which is not working there because /opt/rke2/bin is not in $PATH after rke2 setup.

So there are imho 2 options:
- extend the rke2 installation by adding /opt/rke2/bin to the global PATH variable if it is installed to /opt/rke2
- fix the logs collector to explicitly look also for /opt/rke2/bin/rke2

**Comment by dkeightley** [comment]
@megabreit I've added to the logic in the linked PR, if you have any input about the suggested changes it would be appreciated.

**Comment by megabreit** [comment]
@dkeightley This looks incomplete to me and does not fix the issue. The `which` command in line 144 fails to get the rke2 binary path... because /opt/rke2/bin is not in $PATH.
I checked the docs. In general for manual installations it is allowed to install the rke2 binary in **any** path (not sure how "supported" that is?). But there it is also recommend to add the install path to $PATH. Fun fact: You guys don't do it the recommended way yourself in your own products. RKE2 on SLES 15 with btrfs does not add the rke2 path, and also Harvester is not setting adding path.
 So a universal solution would probably be a bit more complex. Maybe try to get the path from the systemd unit files (e.g. /etc/systemd/system/rke2-server.service -> ExecStart=/opt/rke2/bin/rke2 server)?

**Comment by dkeightley** [comment]
@megabreit Thanks for the feedback, I've added a further commit for line 144. The systemd approach would also be an option, however some installs may run rke2 binaries directly, or via another supervisor process.

The RKE2 install script won't alter the path (even when using /usr/local/bin, etc.), as the install completes it does also prompt a note about updating the PATH. However I understand how this could be different with automation via Harvester, I'll pass this note on to a colleague.

**Comment by megabreit** [comment]
@dkeightley Looks good to me. My 2 usecases seem to be covered now. I'm away from the office until next week, so if you want me to test this, you need to wait til next week.
