### ISSUE TITLE
Update rancher2 log collector to collect SUSE Observability logs

### ISSUE THREAD

**Issue by dnoland1** [rancherlabs/support-tools#317]
Need all logs running in the suse-observability namespace

**Comment by amolkharche13** [comment]
I can see https://stackstate.atlassian.net/browse/STAC-21890 has already been raised from the backend team.

**Comment by amolkharche13** [comment]
I've created the attached script and ran it in the cluster. It collects all relevant information about suse-observability. I'm now waiting for feedback and review from the engineering team.
[suse-observability_logs_collector.zip](https://github.com/user-attachments/files/17753949/suse-observability_logs_collector.zip)

**Comment by dnoland1** [comment]
Could we just update the existing script to include the namespace(s) used by SUSE Observability rather that having a separate script?

**Comment by amolkharche13** [comment]
Sure, I will update the existing script to include the namespace(s) used by SUSE Observability.
I'm just thinking if we have any script for SUSE Observability that can be available for all platforms like rancher, DigitalOcean, On-prem cluster, etc.

**Comment by dnoland1** [comment]
Yes, that will be useful too, but let's keep the scope of this issue to the existing script.

**Comment by amolkharche13** [comment]
Tested in rancher and hosted rancher cluster, It works fine and can collect logs related to the suse-observability namespace.
Here is the sample file 
[rancher-testing-cluster-pool1-glqjw-7k4cm-2024-11-18_05_34_16.tar.gz](https://github.com/user-attachments/files/17795455/rancher-testing-cluster-pool1-glqjw-7k4cm-2024-11-18_05_34_16.tar.gz)

**Comment by amolkharche13** [comment]
https://github.com/rancherlabs/support-tools/pull/322
