### ISSUE TITLE
Rancher 2.x Log Collector Support for RancherOS

### ISSUE THREAD

**Issue by oxr463** [rancherlabs/support-tools#65]
> My nodes are running rancheros. Will the script work there?

**Comment by oxr463** [comment]
Testing in Vagrant, (See: https://github.com/rancher/quickstart/blob/master/vagrant/Vagrantfile).

**Comment by dnoland1** [comment]
Yes, log collector script should work on RancherOS. If it doesn't let us know what error you hit.

**Comment by oxr463** [comment]
On RancherOS v1.5.1, I can run the collector without any issues, but I cannot extract the archive:

```sh
tar xf server-01-2020-11-05_19_51_11.tar.gz 
tar: invalid tar magic

tar --version
tar (busybox) 1.27.2
```

**Comment by oxr463** [comment]
See also: https://raw.githubusercontent.com/rancher/os/master/scripts/tools/collect_rancheros_info.sh

**Comment by dnoland1** [comment]
Can you add the `z` flag to the tar command or first try ungzip first? Some older and stripped down versions of tar don't recognize gzip compression.
