### ISSUE TITLE
option to tail filesystem logs

### ISSUE THREAD

**Issue by nayrnet** [rancherlabs/support-tools#82]
We can limit the scope on the k8s logs via days, but log files gathered off the filesystem such as those in /var/log are grabbed in their entirety.. on space limited nodes I would like an option to tail those files into smaller bundles.. ie, -t 2000 parameter to grab last 2k lines of any files that cannot be truncated by the -s <days> param.

**Comment by nayrnet** [comment]
also should not grab up any compressed/rotated logs when using the tail option

**Comment by dkeightley** [comment]
Should be fixed with https://github.com/rancherlabs/support-tools/pull/257
